/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'user_project' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "cs32f10x.h"

/* ChipSea::Device:StdPeriph Drivers:ADC@2.1.0 */
#define RTE_DEVICE_STDPERIPH_ADC
/* ChipSea::Device:StdPeriph Drivers:BKP@2.1.0 */
#define RTE_DEVICE_STDPERIPH_BKP
/* ChipSea::Device:StdPeriph Drivers:CAN@2.1.0 */
#define RTE_DEVICE_STDPERIPH_CAN
/* ChipSea::Device:StdPeriph Drivers:CRC@2.1.0 */
#define RTE_DEVICE_STDPERIPH_CRC
/* ChipSea::Device:StdPeriph Drivers:DEBUG@2.1.0 */
#define RTE_DEVICE_STDPERIPH_DEBUG
/* ChipSea::Device:StdPeriph Drivers:DMA@2.1.0 */
#define RTE_DEVICE_STDPERIPH_DMA
/* ChipSea::Device:StdPeriph Drivers:EXTI@2.1.0 */
#define RTE_DEVICE_STDPERIPH_EXTI
/* ChipSea::Device:StdPeriph Drivers:FWDT@2.1.0 */
#define RTE_DEVICE_STDPERIPH_FWDT
/* ChipSea::Device:StdPeriph Drivers:Flash@2.1.0 */
#define RTE_DEVICE_STDPERIPH_FLASH
/* ChipSea::Device:StdPeriph Drivers:Framework@2.1.0 */
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
/* ChipSea::Device:StdPeriph Drivers:GPIO@2.1.0 */
#define RTE_DEVICE_STDPERIPH_GPIO
/* ChipSea::Device:StdPeriph Drivers:I2C@2.1.0 */
#define RTE_DEVICE_STDPERIPH_I2C
/* ChipSea::Device:StdPeriph Drivers:PMU@2.1.0 */
#define RTE_DEVICE_STDPERIPH_PMU
/* ChipSea::Device:StdPeriph Drivers:RCU@2.1.0 */
#define RTE_DEVICE_STDPERIPH_RCU
/* ChipSea::Device:StdPeriph Drivers:RTC@2.1.0 */
#define RTE_DEVICE_STDPERIPH_RTC
/* ChipSea::Device:StdPeriph Drivers:SPI@2.1.0 */
#define RTE_DEVICE_STDPERIPH_SPI
/* ChipSea::Device:StdPeriph Drivers:TIM@2.1.0 */
#define RTE_DEVICE_STDPERIPH_TIM
/* ChipSea::Device:StdPeriph Drivers:USART@2.1.0 */
#define RTE_DEVICE_STDPERIPH_USART
/* ChipSea::Device:StdPeriph Drivers:WWDT@2.1.0 */
#define RTE_DEVICE_STDPERIPH_WWDT


#endif /* RTE_COMPONENTS_H */
